### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Broshan1337** [Squatch55/Digispark-Payload#1]
ltr why

**Comment by Broshan1337** [comment]
![image](https://user-images.githubusercontent.com/83551798/173898409-4091123f-61a8-4c10-a5e2-614996601252.png)

**Comment by Broshan1337** [comment]
![image](https://user-images.githubusercontent.com/83551798/173898427-8e01f666-cd57-4770-beb5-2bfb6d17f682.png)

**Comment by Broshan1337** [comment]
who u trying to rat w quasar

**Comment by Squatch55** [comment]
Its just for tutorial..
